/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as PpdbRouteImport } from './routes/ppdb'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileVisionRouteImport } from './routes/profile.vision'
import { Route as ProfileStructureRouteImport } from './routes/profile.structure'
import { Route as ProfileHistoryRouteImport } from './routes/profile.history'
import { Route as NewsSchoolRouteImport } from './routes/news.school'
import { Route as NewsAnnouncementsRouteImport } from './routes/news.announcements'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as NewsAnnouncementsSlugRouteImport } from './routes/news.announcements.$slug'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const PpdbRoute = PpdbRouteImport.update({
  id: '/ppdb',
  path: '/ppdb',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileVisionRoute = ProfileVisionRouteImport.update({
  id: '/profile/vision',
  path: '/profile/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileStructureRoute = ProfileStructureRouteImport.update({
  id: '/profile/structure',
  path: '/profile/structure',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHistoryRoute = ProfileHistoryRouteImport.update({
  id: '/profile/history',
  path: '/profile/history',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSchoolRoute = NewsSchoolRouteImport.update({
  id: '/news/school',
  path: '/news/school',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsAnnouncementsRoute = NewsAnnouncementsRouteImport.update({
  id: '/news/announcements',
  path: '/news/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsAnnouncementsSlugRoute = NewsAnnouncementsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsAnnouncementsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/ppdb': typeof PpdbRoute
  '/teachers': typeof TeachersRoute
  '/admin/login': typeof AdminLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/announcements': typeof NewsAnnouncementsRouteWithChildren
  '/news/school': typeof NewsSchoolRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/structure': typeof ProfileStructureRoute
  '/profile/vision': typeof ProfileVisionRoute
  '/news/announcements/$slug': typeof NewsAnnouncementsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/ppdb': typeof PpdbRoute
  '/teachers': typeof TeachersRoute
  '/admin/login': typeof AdminLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/announcements': typeof NewsAnnouncementsRouteWithChildren
  '/news/school': typeof NewsSchoolRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/structure': typeof ProfileStructureRoute
  '/profile/vision': typeof ProfileVisionRoute
  '/news/announcements/$slug': typeof NewsAnnouncementsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/ppdb': typeof PpdbRoute
  '/teachers': typeof TeachersRoute
  '/admin/login': typeof AdminLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/announcements': typeof NewsAnnouncementsRouteWithChildren
  '/news/school': typeof NewsSchoolRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/structure': typeof ProfileStructureRoute
  '/profile/vision': typeof ProfileVisionRoute
  '/news/announcements/$slug': typeof NewsAnnouncementsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/facilities'
    | '/gallery'
    | '/ppdb'
    | '/teachers'
    | '/admin/login'
    | '/news/$slug'
    | '/news/announcements'
    | '/news/school'
    | '/profile/history'
    | '/profile/structure'
    | '/profile/vision'
    | '/news/announcements/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/facilities'
    | '/gallery'
    | '/ppdb'
    | '/teachers'
    | '/admin/login'
    | '/news/$slug'
    | '/news/announcements'
    | '/news/school'
    | '/profile/history'
    | '/profile/structure'
    | '/profile/vision'
    | '/news/announcements/$slug'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/facilities'
    | '/gallery'
    | '/ppdb'
    | '/teachers'
    | '/admin/login'
    | '/news/$slug'
    | '/news/announcements'
    | '/news/school'
    | '/profile/history'
    | '/profile/structure'
    | '/profile/vision'
    | '/news/announcements/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  FacilitiesRoute: typeof FacilitiesRoute
  GalleryRoute: typeof GalleryRoute
  PpdbRoute: typeof PpdbRoute
  TeachersRoute: typeof TeachersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsAnnouncementsRoute: typeof NewsAnnouncementsRouteWithChildren
  NewsSchoolRoute: typeof NewsSchoolRoute
  ProfileHistoryRoute: typeof ProfileHistoryRoute
  ProfileStructureRoute: typeof ProfileStructureRoute
  ProfileVisionRoute: typeof ProfileVisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppdb': {
      id: '/ppdb'
      path: '/ppdb'
      fullPath: '/ppdb'
      preLoaderRoute: typeof PpdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/vision': {
      id: '/profile/vision'
      path: '/profile/vision'
      fullPath: '/profile/vision'
      preLoaderRoute: typeof ProfileVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/structure': {
      id: '/profile/structure'
      path: '/profile/structure'
      fullPath: '/profile/structure'
      preLoaderRoute: typeof ProfileStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/history': {
      id: '/profile/history'
      path: '/profile/history'
      fullPath: '/profile/history'
      preLoaderRoute: typeof ProfileHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/school': {
      id: '/news/school'
      path: '/news/school'
      fullPath: '/news/school'
      preLoaderRoute: typeof NewsSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/announcements': {
      id: '/news/announcements'
      path: '/news/announcements'
      fullPath: '/news/announcements'
      preLoaderRoute: typeof NewsAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/announcements/$slug': {
      id: '/news/announcements/$slug'
      path: '/$slug'
      fullPath: '/news/announcements/$slug'
      preLoaderRoute: typeof NewsAnnouncementsSlugRouteImport
      parentRoute: typeof NewsAnnouncementsRoute
    }
  }
}

interface NewsAnnouncementsRouteChildren {
  NewsAnnouncementsSlugRoute: typeof NewsAnnouncementsSlugRoute
}

const NewsAnnouncementsRouteChildren: NewsAnnouncementsRouteChildren = {
  NewsAnnouncementsSlugRoute: NewsAnnouncementsSlugRoute,
}

const NewsAnnouncementsRouteWithChildren =
  NewsAnnouncementsRoute._addFileChildren(NewsAnnouncementsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  FacilitiesRoute: FacilitiesRoute,
  GalleryRoute: GalleryRoute,
  PpdbRoute: PpdbRoute,
  TeachersRoute: TeachersRoute,
  AdminLoginRoute: AdminLoginRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsAnnouncementsRoute: NewsAnnouncementsRouteWithChildren,
  NewsSchoolRoute: NewsSchoolRoute,
  ProfileHistoryRoute: ProfileHistoryRoute,
  ProfileStructureRoute: ProfileStructureRoute,
  ProfileVisionRoute: ProfileVisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
