/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PpdbRouteImport } from './routes/ppdb'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PpdbRoute = PpdbRouteImport.update({
  id: '/ppdb',
  path: '/ppdb',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/ppdb': typeof PpdbRoute
  '/profile': typeof ProfileRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/ppdb': typeof PpdbRoute
  '/profile': typeof ProfileRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/ppdb': typeof PpdbRoute
  '/profile': typeof ProfileRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/facilities'
    | '/gallery'
    | '/news'
    | '/ppdb'
    | '/profile'
    | '/teachers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/facilities'
    | '/gallery'
    | '/news'
    | '/ppdb'
    | '/profile'
    | '/teachers'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/facilities'
    | '/gallery'
    | '/news'
    | '/ppdb'
    | '/profile'
    | '/teachers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  FacilitiesRoute: typeof FacilitiesRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  PpdbRoute: typeof PpdbRoute
  ProfileRoute: typeof ProfileRoute
  TeachersRoute: typeof TeachersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppdb': {
      id: '/ppdb'
      path: '/ppdb'
      fullPath: '/ppdb'
      preLoaderRoute: typeof PpdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  FacilitiesRoute: FacilitiesRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  PpdbRoute: PpdbRoute,
  ProfileRoute: ProfileRoute,
  TeachersRoute: TeachersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
